const DATA_PATH='./dashboard-data.json';
const $=id=>document.getElementById(id);
const norm=v=>String(v??'').trim();
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const dateKey=v=>{if(!v)return'';const s=String(v).trim().replace(/[/.]/g,'-');const m=s.match(/(20\d{2})-(\d{1,2})-(\d{1,2})/);return m?`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`:''};
const taipeiToday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function findSheet(data,keys){return Object.keys(data.sheets||{}).find(n=>keys.some(k=>n.includes(k)))}
function firstField(r,names){for(const n of names){const k=Object.keys(r||{}).find(x=>x.trim()===n||x.includes(n));if(k&&norm(r[k])!=='')return r[k]}return''}
function todayRows(rs,today){return rs.filter(r=>dateKey(firstField(r,['日期','Date']))===today)}
function sumField(rs,names){return rs.reduce((a,r)=>a+(num(firstField(r,names))??0),0)}
function setMetric(id,v,fallback='—'){$(id).textContent=v===null||v===undefined||v===''?fallback:v}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderMeals(rs){const box=$('meals');box.innerHTML='';if(!rs.length){box.innerHTML='<div class="row"><div class="left"><b>尚無飲食資料</b><p>今天的餐點尚未寫入工作簿。</p></div></div>';$('mealCount').textContent='0 筆';return}rs.forEach(r=>{const meal=norm(firstField(r,['餐別','餐次']))||'飲食';const food=norm(firstField(r,['餐點','內容','食物']))||'未命名餐點';const p=firstField(r,['蛋白質']);const c=firstField(r,['熱量','卡路里']);const note=norm(firstField(r,['備註','來源']));box.insertAdjacentHTML('beforeend',`<div class="row"><div class="left"><b>${esc(meal)} · ${esc(food)}</b><p>${esc(note||'—')}</p></div><div class="value">${p!==''?`${esc(p)}g`:''}${p!==''&&c!==''?'<br>':''}${c!==''?`${esc(c)} kcal`:''}</div></div>`)});$('mealCount').textContent=`${rs.length} 筆`}
function renderChecks(r){const box=$('checks');box.innerHTML='';if(!r){box.innerHTML='<div class="row"><div class="left"><b>尚無每日檢核</b><p>今天的檢核資料尚未寫入。</p></div></div>';$('checkState').textContent='待補';return}const items=[['零下注',['零下注']],['查看盤口',['查看盤口']],['衝動分數',['衝動分數','衝動']],['完成重訓',['完成重訓','重訓']],['散步分鐘',['散步分鐘','散步']],['睡眠小時',['睡眠小時','睡眠']]];let filled=0;items.forEach(([label,names])=>{const v=firstField(r,names);if(norm(v)!=='')filled++;box.insertAdjacentHTML('beforeend',`<div class="check"><span>${label}</span><b>${esc(norm(v)||'—')}</b></div>`)});$('checkState').textContent=`${filled}/${items.length}`}
function renderWorkouts(rs){const box=$('workouts');box.innerHTML='';if(!rs.length){box.innerHTML='<div class="row"><div class="left"><b>今天沒有重訓資料</b><p>如果每日檢核已標示未重訓，這是正常狀態。</p></div></div>';$('workoutState').textContent='0 組';return}rs.forEach(r=>{const ex=norm(firstField(r,['動作','項目']))||'動作';const set=norm(firstField(r,['組次','組']))||'';const w=firstField(r,['重量']);const reps=firstField(r,['次數']);const rpe=firstField(r,['RPE']);box.insertAdjacentHTML('beforeend',`<div class="row"><div class="left"><b>${esc(ex)}${set?` · 第 ${esc(set)} 組`:''}</b><p>${rpe!==''?`RPE ${esc(rpe)}`:'RPE 未記錄'}</p></div><div class="value">${w!==''?`${esc(w)} kg`:''}${reps!==''?` × ${esc(reps)}`:''}</div></div>`)});$('workoutState').textContent=`${rs.length} 組`}
function renderTrend(foodRows){const grouped=new Map;foodRows.forEach(r=>{const d=dateKey(firstField(r,['日期','Date']));if(!d)return;const g=grouped.get(d)||{p:0,c:0};g.p+=num(firstField(r,['蛋白質']))||0;g.c+=num(firstField(r,['熱量','卡路里']))||0;grouped.set(d,g)});const days=[...grouped.keys()].sort().slice(-7);new Chart($('trendChart'),{type:'line',data:{labels:days.map(d=>d.slice(5)),datasets:[{label:'蛋白質(g)',data:days.map(d=>grouped.get(d).p),yAxisID:'y'},{label:'熱量(kcal)',data:days.map(d=>grouped.get(d).c),yAxisID:'y1'}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:'#95a3bd'}}},scales:{x:{ticks:{color:'#95a3bd'},grid:{color:'#26324d'}},y:{ticks:{color:'#95a3bd'},grid:{color:'#26324d'}},y1:{position:'right',ticks:{color:'#95a3bd'},grid:{drawOnChartArea:false}}}}})}
async function main(){const today=taipeiToday();$('todayLabel').textContent=`台北時間 ${today}`;try{const res=await fetch(`${DATA_PATH}?v=${Date.now()}`);if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=await res.json();const foodName=findSheet(data,['飲食']),checkName=findSheet(data,['每日檢核','檢核']),workName=findSheet(data,['重訓']);const foodRows=foodName?data.sheets[foodName].rows:[],checkRows=checkName?data.sheets[checkName].rows:[],workRows=workName?data.sheets[workName].rows:[];const tf=todayRows(foodRows,today),tc=todayRows(checkRows,today),tw=todayRows(workRows,today);setMetric('protein',sumField(tf,['蛋白質'])||0);setMetric('calories',sumField(tf,['熱量','卡路里'])||0);const cr=tc[0];setMetric('sleep',cr?firstField(cr,['睡眠小時','睡眠']):'');setMetric('walk',cr?firstField(cr,['散步分鐘','散步']):'');setMetric('zeroBet',cr?firstField(cr,['零下注']):'');setMetric('urge',cr?firstField(cr,['衝動分數','衝動']):'');renderMeals(tf);renderChecks(cr);renderWorkouts(tw);renderTrend(foodRows);const allDates=[...new Set([...foodRows,...checkRows,...workRows].map(r=>dateKey(firstField(r,['日期','Date']))).filter(Boolean))].sort();const first=allDates[0]||today;const day=Math.max(1,Math.min(30,Math.floor((Date.parse(today+'T00:00:00Z')-Date.parse(first+'T00:00:00Z'))/86400000)+1));const pct=Math.round(day/30*100);$('dayLabel').textContent=`Day ${day} / 30`;$('progressPct').textContent=`${pct}%`;$('progressBar').style.width=`${pct}%`;$('statusBanner').textContent=`已載入：${[foodName,checkName,workName].filter(Boolean).join(' / ')||'找不到預期工作表'}`;$('updatedAt').textContent=`資料產生 ${new Date(data.generated_at).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})}`}catch(e){console.error(e);$('statusBanner').textContent=`讀取 dashboard-data.json 失敗：${e.message}`;$('statusBanner').classList.add('bad')}}main();
